"""
Specialized Incident Playbooks.

Each playbook is a curated, ordered set of actions for a specific incident
type. These are injected into the LLM prompt as authoritative reference
material (same trust tier as the legal knowledge base) so the model's
"Immediate Actions" / "Next 24 Hours" / "Evidence to Preserve" sections are
grounded in reviewed guidance rather than improvised each time — while the
actual prose is still generated by the model so it can adapt to the
specifics of the case.

Playbooks are looked up via message-text markers first (fine-grained,
e.g. "Instagram hacked" vs "WhatsApp hacked"), falling back to a coarse
category-level match for a few unambiguous categories.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional


@dataclass
class Playbook:
    name: str
    immediate_actions: List[str] = field(default_factory=list)
    next_24_hours: List[str] = field(default_factory=list)
    evidence_to_preserve: List[str] = field(default_factory=list)
    prevention: List[str] = field(default_factory=list)


PLAYBOOKS: Dict[str, Playbook] = {

    "upi_fraud": Playbook(
        name="UPI Fraud",
        immediate_actions=[
            "Call your bank's fraud helpline immediately and request a transaction block/reversal request.",
            "Call 1930 (National Cyber Crime Helpline) — fastest route to a freeze request on the receiving account.",
            "Do NOT make any further UPI payments to 'reverse' or 'verify' the transaction — that is a common follow-up scam.",
            "Change your UPI PIN if there's any chance it was shared or entered on a fake app/link.",
        ],
        next_24_hours=[
            "File a complaint at cybercrime.gov.in with the transaction ID/UTR number.",
            "Request a written transaction dispute from your bank (in-app or branch).",
            "Check linked accounts/cards for any other unauthorized activity.",
        ],
        evidence_to_preserve=[
            "Transaction ID / UTR number", "Screenshot of the payment confirmation",
            "Screenshot of the scammer's UPI ID or QR code", "SMS/bank alert for the debit",
            "Any chat/call log with the scammer",
        ],
        prevention=[
            "Never scan a QR code or enter your UPI PIN to *receive* money — PIN is only for sending.",
            "Verify payee name shown before confirming any UPI payment.",
        ],
    ),

    "qr_scam": Playbook(
        name="QR Code Scam",
        immediate_actions=[
            "Do not scan or complete the QR payment if you haven't already.",
            "If already scanned and PIN entered: call bank fraud helpline + 1930 immediately.",
            "Remember: scanning a QR and entering PIN can authorize an outgoing payment — QR/PIN entry is never needed to *receive* money.",
        ],
        next_24_hours=[
            "File complaint at cybercrime.gov.in with the QR image/screenshot if saved.",
            "Report the seller/contact on the platform (e.g. OLX, marketplace) if the scam originated there.",
        ],
        evidence_to_preserve=["QR code image", "Chat with the scammer", "Transaction ID if payment went through"],
        prevention=["Meet in person or use platform-protected payment for online marketplace deals."],
    ),

    "investment_scam": Playbook(
        name="Investment / Crypto Scam",
        immediate_actions=[
            "Stop all further payments immediately — 'unlocking' fees or 'tax' payments to withdraw are always fake.",
            "Call 1930 and report at cybercrime.gov.in with all transaction details.",
        ],
        next_24_hours=[
            "Gather every transaction ID and the app/website/Telegram group used.",
            "Check if the platform is listed on SEBI/RBI's public list of unauthorized entities.",
            "Warn friends/family who may be in the same group — these scams target networks.",
        ],
        evidence_to_preserve=["Screenshots of the app/dashboard", "All transaction IDs", "Chat history with the 'advisor'", "Group/channel name and links"],
        prevention=["Guaranteed high returns with no risk is always a red flag — verify SEBI registration before investing."],
    ),

    "job_scam": Playbook(
        name="Fake Job Scam",
        immediate_actions=[
            "Stop sending any further 'registration' or 'training' fees.",
            "Do not share bank details or ID documents if you haven't already.",
        ],
        next_24_hours=[
            "Report at cybercrime.gov.in with the job posting/recruiter details.",
            "Report the fake listing on the platform it was posted on (LinkedIn/Naukri/WhatsApp group).",
        ],
        evidence_to_preserve=["Job offer message/email", "Payment receipts", "Recruiter's phone number/profile"],
        prevention=["Legitimate employers never ask candidates to pay for a job offer."],
    ),

    "fake_loan_app": Playbook(
        name="Fake Loan App / Loan Harassment",
        immediate_actions=[
            "Stop making any payments demanded outside your original agreed loan terms.",
            "Revoke the app's contacts/photos/storage permissions immediately (Settings > Apps > Permissions), then uninstall.",
            "Do not respond to threats — harassment/morphed-photo threats from loan apps are illegal regardless of any amount owed.",
        ],
        next_24_hours=[
            "Report at cybercrime.gov.in and to RBI's Sachet portal (for unauthorized lending apps).",
            "Inform close contacts in advance that you may receive harassing messages about you, so they aren't caught off guard.",
            "File a police complaint if you are being threatened or contacts are being messaged.",
        ],
        evidence_to_preserve=["App name/screenshots", "All threatening messages/calls", "Payment records"],
        prevention=["Only use RBI-registered NBFC/bank lending apps; check for a valid physical address and RBI registration."],
    ),

    "sim_swap": Playbook(
        name="SIM Swap",
        immediate_actions=[
            "Call your telecom provider's helpline immediately to report unauthorized SIM swap and request a block.",
            "Call your bank(s) to freeze/monitor accounts — SIM swap is usually a precursor to account takeover via OTP interception.",
            "Call 1930 if any money has already moved.",
        ],
        next_24_hours=[
            "Visit telecom provider's store with ID to reissue your legitimate SIM.",
            "Change passwords on email and banking apps from a trusted device once you regain number control.",
            "File complaint at cybercrime.gov.in.",
        ],
        evidence_to_preserve=["Screenshot of 'no service' timestamp", "Bank/telecom SMS alerts", "Any prior phishing message that may have led to this"],
        prevention=["Enable SIM-lock/PIN with your telecom provider; avoid sharing SIM/Aadhaar details over calls."],
    ),

    "instagram_hacked": Playbook(
        name="Instagram Account Hacked",
        immediate_actions=[
            "Go to Instagram's 'My account was hacked' recovery flow (instagram.com/hacked) immediately.",
            "Check for a linked email/phone change alert — if you still have email access, reverse it via the email link.",
            "Warn close contacts not to trust messages/payment requests from the account until recovered.",
        ],
        next_24_hours=[
            "Complete Instagram's identity verification (video selfie or ID) if prompted.",
            "Once recovered: enable two-factor authentication, log out of all other sessions.",
            "File complaint at cybercrime.gov.in if the account was used to scam contacts.",
        ],
        evidence_to_preserve=["Screenshot of 'account not found' or unauthorized change email", "Any scam messages sent from the account to others"],
        prevention=["Enable 2FA via authenticator app, not SMS if SIM swap risk exists."],
    ),

    "whatsapp_hacked": Playbook(
        name="WhatsApp Account Hacked",
        immediate_actions=[
            "Immediately reinstall WhatsApp on your own phone with your number — this auto-logs out the attacker's device.",
            "Enable Two-Step Verification (Settings > Account > Two-step verification) right after regaining access.",
            "Warn your contacts immediately — this account is very likely being used to run a 'send me money urgently' scam on your friends/family right now.",
        ],
        next_24_hours=[
            "Report the incident to WhatsApp support if reinstall doesn't restore access.",
            "File complaint at cybercrime.gov.in, especially if any contact sent money believing it was you.",
        ],
        evidence_to_preserve=["Screenshots of any scam messages sent from your account", "Reports from contacts who received suspicious messages"],
        prevention=["Never share the 6-digit WhatsApp verification code with anyone, even someone claiming to be WhatsApp support."],
    ),

    "email_hacked": Playbook(
        name="Email Compromise",
        immediate_actions=[
            "Try password reset immediately via 'Forgot Password' using your recovery phone/email.",
            "If recovery still works: change password, then immediately revoke all active sessions/connected apps.",
            "Check for a changed recovery email/phone — attackers often change this first to lock you out permanently.",
        ],
        next_24_hours=[
            "Enable 2FA once recovered.",
            "Check email for any password-reset chains to other accounts (banking, social media) that may also be compromised.",
            "File complaint at cybercrime.gov.in if the account was used for further fraud.",
        ],
        evidence_to_preserve=["Login alert emails/SMS", "Any fraudulent emails sent from the account"],
        prevention=["Use a unique strong password + authenticator-app 2FA, not SMS-only."],
    ),

    "sextortion": Playbook(
        name="Sextortion / Blackmail with Explicit Content",
        immediate_actions=[
            "Do NOT pay — payment does not stop the threat and often increases demands.",
            "Do NOT delete any messages/screenshots — preserve everything as evidence, even though it feels awful to keep.",
            "Disable 'disappearing messages' in the chat immediately if enabled, so future messages are also preserved.",
            "Stop responding to the attacker directly — anything you say can be used to escalate.",
        ],
        next_24_hours=[
            "Report to the platform immediately (Instagram/Facebook/etc. have dedicated non-consensual content reporting).",
            "File complaint at cybercrime.gov.in (dedicated child/women crime category, or general cybercrime flow) or call 1930.",
            "If a minor is involved, report to Childline (1098) and NCPCR in addition to cybercrime channels.",
            "Consider contacting local police to file an FIR — sextortion is a criminal offence.",
        ],
        evidence_to_preserve=["All chat screenshots with timestamps", "The attacker's profile/username/phone number", "Any payment demands received"],
        prevention=["Common tactic: attacker builds trust fast then requests video call/photos — be cautious of accelerated intimacy from new online contacts."],
    ),

    "cyberbullying": Playbook(
        name="Cyberbullying / Online Harassment",
        immediate_actions=[
            "Do not respond or engage with the bully — this often fuels further harassment.",
            "Screenshot the abusive content/messages before blocking, so evidence isn't lost.",
            "Block the account(s) involved.",
        ],
        next_24_hours=[
            "Report the content/account on the platform using its harassment/bullying report tool.",
            "If this is happening at school/college/workplace, escalate to a trusted teacher, counselor, or HR — most institutions have an anti-bullying policy.",
            "File complaint at cybercrime.gov.in if the harassment is severe, repeated, or threatening.",
        ],
        evidence_to_preserve=["Screenshots with usernames and timestamps visible", "List of dates/frequency if repeated"],
        prevention=["Set profiles to private, restrict who can comment/message, and periodically review follower lists."],
    ),

    "ransomware": Playbook(
        name="Ransomware",
        immediate_actions=[
            "Disconnect the device from the internet/network immediately to stop further spread or exfiltration.",
            "Do NOT pay the ransom — there's no guarantee of decryption, and payment funds further attacks.",
            "Do not reboot or run 'cleanup' tools yet if this is a work device — those can destroy forensic evidence.",
        ],
        next_24_hours=[
            "Report to CERT-In (cert-in.org.in) and file complaint at cybercrime.gov.in.",
            "Check if a free decryptor exists for the specific ransomware strain (e.g. via nomoreransom.org).",
            "If a work/organization device, notify IT/security team immediately.",
        ],
        evidence_to_preserve=["Ransom note screenshot", "Ransomware strain/file extension of encrypted files", "Any wallet address given for payment"],
        prevention=["Maintain offline backups; keep OS/software patched."],
    ),

    "malware": Playbook(
        name="Malware / Device Infection",
        immediate_actions=[
            "Disconnect from Wi-Fi/mobile data to limit further data exfiltration.",
            "Run a reputable antivirus/anti-malware scan; if a remote-access app (AnyDesk/TeamViewer) was installed by a scammer, uninstall it immediately.",
        ],
        next_24_hours=[
            "Change passwords for important accounts from a different, clean device.",
            "Monitor bank statements closely for the next few weeks.",
            "File complaint at cybercrime.gov.in if financial loss or data theft occurred.",
        ],
        evidence_to_preserve=["App name if remote-access software was involved", "Any suspicious link/attachment that triggered it"],
        prevention=["Never install remote-access apps at the request of an unsolicited caller claiming to be tech/bank support."],
    ),

    "child_online_abuse": Playbook(
        name="Child Online Safety Incident",
        immediate_actions=[
            "Prioritize the child's immediate safety and emotional support over investigation details.",
            "Do not ask the child for graphic details — preserve evidence via screenshots taken calmly, not through re-questioning the child repeatedly.",
            "Report immediately via cybercrime.gov.in (dedicated child-related crime category) or call Childline India: 1098.",
        ],
        next_24_hours=[
            "File a police complaint — this is treated with highest priority under law.",
            "Do not confront the perpetrator directly, as this can cause evidence destruction or escalation.",
            "Consider professional counseling support for the child.",
        ],
        evidence_to_preserve=["All chat logs/screenshots", "Usernames/profiles involved", "Platform and account details"],
        prevention=["Enable platform parental controls; have ongoing, non-judgmental conversations with children about online contacts."],
    ),

    "senior_citizen_scam": Playbook(
        name="Senior Citizen Targeted Scam",
        immediate_actions=[
            "Stop all further payments or information sharing immediately.",
            "Call 1930 and the bank fraud helpline right away if money was transferred.",
        ],
        next_24_hours=[
            "File complaint at cybercrime.gov.in with a family member's help if needed.",
            "Set up transaction alerts and, if desired, transaction limits with the bank going forward.",
        ],
        evidence_to_preserve=["Caller's number", "Any app installed at their instruction", "Transaction details"],
        prevention=["Banks/government agencies never ask for OTP, PIN, or remote access over a call — establish this as a simple rule with at-risk family members."],
    ),

    "deepfake": Playbook(
        name="Deepfake / AI Voice Scam",
        immediate_actions=[
            "If a call demanded urgent money transfer using a familiar voice: hang up and call that person back directly on their known number to verify.",
            "If a fake video/image of you is circulating: do not engage with the poster — go straight to platform reporting.",
        ],
        next_24_hours=[
            "Report the content on the platform as impersonation/synthetic media.",
            "File complaint at cybercrime.gov.in.",
            "Warn contacts if a deepfake of you is being used to scam others.",
        ],
        evidence_to_preserve=["The audio/video/image itself", "Source account/number it came from"],
        prevention=["Agree on a family verification phrase for urgent money requests over calls."],
    ),
}

import re

# Fine-grained detection: message-level substrings mapped to a specific
# playbook key, checked before falling back to the broader category-level
# playbook. Order matters — more specific patterns first.
_SUBTYPE_MARKERS = [
    ("instagram_hacked", ["instagram is hacked", "instagram hacked", "hacked my instagram"]),
    ("whatsapp_hacked", ["whatsapp is hacked", "whatsapp hacked", "hacked my whatsapp"]),
    ("email_hacked", ["gmail hacked", "email hacked", "email is hacked", "hacked my email", "hacked my gmail"]),
    ("sim_swap", ["sim swap", "sim card stopped", "sim stopped working", "duplicate sim"]),
    ("ransomware", ["ransomware", "files encrypted", "ransom demand", "ransom note"]),
    ("qr_scam", ["qr code", "scan qr", "scanned a qr"]),
    ("fake_loan_app", ["loan app", "loan harassment", "instant loan app"]),
    ("job_scam", ["job scam", "fake job offer", "registration fee for job", "work from home scam"]),
    ("investment_scam", ["crypto scam", "fake investment", "ponzi", "trading app scam", "guaranteed returns"]),
    ("upi_fraud", ["upi", "gpay", "phonepe", "google pay fraud"]),
    ("malware", ["malware", "virus on my", "device infected", "spyware", "keylogger", "anydesk", "teamviewer"]),
    ("deepfake", ["deepfake", "ai voice", "voice clone", "cloned voice", "fake video of me"]),
    ("cyberbullying", ["bully", "bullying", "mocking", "trolling", "spreading rumors", "harass"]),
    ("child_online_abuse", ["my child", "my kid", "my son", "my daughter", "grooming", "minor", "underage"]),
]

# Sextortion needs flexible matching, not rigid phrases — real messages say
# things like "leak my private photos" or "posted my nude pics", not the
# exact literal strings "leak my photo" / "revenge porn". Checked first,
# before the generic subtype list, since it's high-severity and should not
# be missed due to phrasing variation.
_SEXTORTION_RE = re.compile(
    r"\bsextortion\b|\brevenge porn\b|\bmorphed (?:photo|picture|video)\b"
    r"|\b(?:leak\w*|post\w*|shar\w*|publish\w*|expos\w*|send\w*)\b.{0,30}\b(?:photo|photos|pic|pics|picture|pictures|video|videos|nude|nudes|intimate)\b",
    re.IGNORECASE,
)


def match_playbook(message: str, category_value: Optional[str] = None) -> Optional[Playbook]:
    """Finds the most specific applicable playbook for a message, falling
    back to a category-level match for a few unambiguous categories."""
    text = message.lower()

    if _SEXTORTION_RE.search(text):
        return PLAYBOOKS.get("sextortion")

    for key, markers in _SUBTYPE_MARKERS:
        if any(m in text for m in markers):
            return PLAYBOOKS.get(key)

    category_fallback = {
        "sexually_explicit_content": "sextortion",
        "cyberbullying": "cyberbullying",
        "child_exploitation": "child_online_abuse",
    }
    if category_value in category_fallback:
        return PLAYBOOKS.get(category_fallback[category_value])
    return None


def build_playbook_block(playbook: Optional[Playbook]) -> str:
    """Formats a playbook as a prompt-ready reference block. Empty string
    if no playbook matched (model falls back to general knowledge-base
    guidance in that case)."""
    if playbook is None:
        return ""
    lines = [f"MATCHED INCIDENT PLAYBOOK — {playbook.name} (use this as your authoritative action reference, adapt wording to the conversation but don't contradict it):"]
    if playbook.immediate_actions:
        lines.append("Immediate actions: " + " | ".join(playbook.immediate_actions))
    if playbook.next_24_hours:
        lines.append("Next 24 hours: " + " | ".join(playbook.next_24_hours))
    if playbook.evidence_to_preserve:
        lines.append("Evidence to preserve: " + ", ".join(playbook.evidence_to_preserve))
    if playbook.prevention:
        lines.append("Prevention: " + " | ".join(playbook.prevention))
    return "\n".join(lines)
